### ISSUE TITLE
JIT example does not compile

### ISSUE THREAD

**Issue by saethlin** [gsingh93/llvm#11]
> jit: /home/ben/llvm-5.0.0.src/lib/IR/Instructions.cpp:2087: static llvm::BinaryOperator*
llvm::BinaryOperator::Create(llvm::Instruction::BinaryOps, llvm::Value*, llvm::Value*, const llvm::Twine&, llvm::Instruction*): Assertion `S1->getType() == S2->getType() && "Cannot create binary operator with two operands of differing type!"' failed.

Not exactly sure what's going on here, but LLVM 5.0 recently came out and this crate does use a wildcard version for `llvm-sys` so maybe it was a breaking change?

**Comment by afonso360** [comment]
Hmm, I can't reproduce this.

I just installed llvm 5.0.0 from the arch repos.
The jit example worked with both llvm-sys v50.0.0 and v40.0.4

Can you get me the output of running `cargo build --example jit --verbose`? 
And if possible could you try to pin the package on an old version (eg ^40.0 or ^39.0) and see if you still have the same issue?

We really should have it pinned anyway.

**Comment by tari** [comment]
Arch's binaries are built without assertions enabled, so it makes sense that you're not triggering that assertion with the Arch binary.

> $ llvm-config --assertion-mode
> OFF

I can repro with a custom build that has assertions enabled; the bug title is misleading since it's a runtime error.

> $ cargo run --example jit
>      Running `target/debug/examples/jit`
> jit: ../lib/IR/Instructions.cpp:2087: static llvm::BinaryOperator *llvm::BinaryOperator::Create(llvm::Instruction::BinaryOps, llvm::Value *, llvm::Value *, const llvm::Twine &, llvm::Instruction *): Assertion `S1->getType() == S2->getType() && "Cannot create binary operator with two operands of differing type!"' failed.

---

I can fix the problem by making `b` in the example an i64 constant rather than i8, since otherwise it's attempting to generate an add of an i8 and i64 which isn't legal.

```patch
--- a/examples/jit.rs
+++ b/examples/jit.rs
@@ -24,7 +24,7 @@ fn main() {
     let y = func.get_param(1).unwrap();
     let z = func.get_param(2).unwrap();

-    let b = context.cons(20i8);
+    let b = context.cons(20i64);

     let s1 = builder.build_add(x, b, "s1");
     let s2 = builder.build_add(y, s1, "s2");
```

**Comment by afonso360** [comment]
Hi, Sorry for taking so long to respond, I applied tari's patch, thanks!
